[package]
name = "LED-CLI-Controller"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
rumqttc = "0.24.0"

[profile.release]
incremental = true
debug = true
lto = "fat"


